apiVersion: 1

datasources:
  # Waiting to upgrade to influxdb v2
  # - name: myinfluxdb
  #   type: influxdb
  #   url: http://influxdb:8086
  #   access: 'proxy'
  #   orgId: 1
  #   isDefault: true
  #   version: 2
  #   editable: true
  #   user: ${DB_USERNAME}
  #   jsonData:
  #     dbName: ${BUCKET}
  #   secureJsonData:
  #     password: ${INFLUXDB_API_TOKEN}

  - name: myinfluxdb
    type: influxdb
    access: proxy
    database: k6
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
